version: 1.0.1.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
branches:
  only:
    - master
build_script:
- cmd: >-
    nuget restore .\VMFirstNav.sln

    powershell .\bootstrapper.ps1 -Target NuGetPack -Verbosity diagnostic
artifacts:
- path: '*.nupkg'
  name: NuGet