version: 1.0.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    nuget restore .\VMFirstNav.sln

    powershell .\bootstrapper.ps1 -Target NuGetPack -Verbosity diagnostic
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: dJdf3VFwuaIH8oXgb8e1O0CbUu1M+FgSYe+ocMoCqGqC4V8fPkZoJ54NL4xP4sth
  skip_symbols: true
  symbol_server:
  artifact: /. *\.nupkg/
